In [ ]:
from google.colab import drive
import pandas as pd
import numpy as np

drive.mount("/content/drive",force_remount=True)
path="/content/drive/My Drive/data/"
df = pd.read_csv(path+"digit.csv", header=None)

Mounted at /content/drive


In [ ]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,784
count,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,...,500.00000,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.000000
mean,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.22000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.500000
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.91935,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.875158
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.000000
50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.500000
75%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.000000
max,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,110.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.000000


In [ ]:
features = df.iloc[:,:-1]
label = df.iloc[:,-1]
#print(X.shape, y.shape)

In [ ]:
from sklearn.model_selection import train_test_split
# Split all -> train, test
X_train, X_test, y_train, y_test = train_test_split(features,label,test_size=0.25,random_state=555)
# Spli train -> train, validate
#X_train, X_validate, y_train, y_validate = train_test_split(X,y, train_size=0.8,random_state=555)


In [ ]:
# Scaler
from sklearn.preprocessing import StandardScaler, MinMaxScaler
scaler = [StandardScaler(), MinMaxScaler()]

In [ ]:
# Dimension reduction
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
pca = PCA()
lda = LinearDiscriminantAnalysis()

In [115]:
# Classifier
from sklearn.linear_model import LogisticRegression, Perceptron
from sklearn.naive_bayes import GaussianNB

clf0 = LogisticRegression()
clf1 = GaussianNB()
clf2 = Perceptron(max_iter=100,eta0=0.1,random_state=555,fit_intercept=True,alpha=0.1)
clf = [clf0,clf1,clf2]

In [ ]:
from sklearn.pipeline import Pipeline
# this steps are just place holder
steps = [("scaler", scaler[0]),
         ("dim_reduction", pca),
         ("classify", clf0)]
pipeline = Pipeline(steps)

In [ ]:
param_grid = [
    {
        "scaler": scaler,
        "dim_reduction": [pca],
        "dim_reduction__n_components": [0.9, 0.95, 0.99, 0.999],
        "classify": clf
    },
    {
        "scaler": scaler,
        "dim_reduction": [lda],
        "dim_reduction__n_components": [2, 3, 4, 5],
        "classify": clf
    }
]


In [ ]:
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(pipeline, param_grid=param_grid,cv=5, scoring="accuracy")
grid.fit(X_train,y_train)
y_pred = grid.predict(X_test)

In [ ]:
print(grid.best_estimator_)
print(grid.best_params_)
print(grid.best_score_)

Pipeline(steps=[('scaler', MinMaxScaler()),
                ('dim_reduction', PCA(n_components=0.99)),
                ('classify', LogisticRegression())])
{'classify': LogisticRegression(), 'dim_reduction': PCA(), 'dim_reduction__n_components': 0.99, 'scaler': MinMaxScaler()}
0.8666666666666668


In [118]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      1.00      0.84         8
           1       0.77      0.77      0.77        13
           2       0.56      0.62      0.59         8
           3       0.90      1.00      0.95         9
           4       0.77      0.83      0.80        12
           5       0.86      0.43      0.57        14
           6       0.88      0.93      0.90        15
           7       0.81      0.87      0.84        15
           8       0.83      0.67      0.74        15
           9       0.83      0.94      0.88        16

    accuracy                           0.80       125
   macro avg       0.79      0.81      0.79       125
weighted avg       0.81      0.80      0.79       125



In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_pred, y_test))

[[ 8  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  1  2  1  0  1  0]
 [ 0  2  4  0  1  0  0  0  1  0]
 [ 0  0  0  9  0  1  0  0  0  0]
 [ 0  0  1  0 10  0  0  1  1  0]
 [ 0  0  0  0  0  9  0  0  0  0]
 [ 0  0  0  0  0  0 14  0  0  0]
 [ 0  0  3  0  0  0  0 14  0  0]
 [ 0  0  0  0  0  0  0  0 12  0]
 [ 0  0  0  0  0  2  0  0  0 16]]
